# Generated by Django 4.2.6 on 2023-11-13 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
